version: '3'

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=123456
  nginx:
    image: nginx:1.15
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/code/static
      - ./media:/code/media
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - PORT=8000
      - POSTGRES_CONN_STRING=postgres://postgres:123456@postgres:5432/postgres
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py collectstatic --noinput &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    depends_on:
      - postgres
      - nginx
