site_name: django_kube
site_description: just testing kubernetes on django
repo_url: https://github.com/aindong/django_kube
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/aindong">aindong</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
