apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    holdings.yoyo.service: nginx
  name: nginx
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    holdings.yoyo.service: nginx
  type: NodePort
status:
  loadBalancer: {}