apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    holdings.yoyo.service: postgres
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    holdings.yoyo.service: postgres
status:
  loadBalancer: {}
